name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: testPrivate
      id: testprivate
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testPrivate
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testPrivate"
        timeout: 10
        max-score: 4
    - name: testGetName
      id: testgetname
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testGetName
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testGetName"
        timeout: 10
        max-score: 4
    - name: testSetName
      id: testsetname
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testSetName
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testSetName"
        timeout: 10
        max-score: 4
    - name: testGetHP
      id: testgethp
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testGetHP
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testGetHp"
        timeout: 10
        max-score: 4
    - name: testSetHp
      id: testsethp
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testSetHp
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testSetHp"
        timeout: 10
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTPRIVATE_RESULTS: "${{steps.testprivate.outputs.result}}"
        TESTGETNAME_RESULTS: "${{steps.testgetname.outputs.result}}"
        TESTSETNAME_RESULTS: "${{steps.testsetname.outputs.result}}"
        TESTGETHP_RESULTS: "${{steps.testgethp.outputs.result}}"
        TESTSETHP_RESULTS: "${{steps.testsethp.outputs.result}}"
      with:
        runners: testprivate,testgetname,testsetname,testgethp,testsethp
